from repositories.teacher import TeacherRepository
from repositories.student import StudentRepository
from repositories.subject import SubjectRepository
from repositories.cls import ClassRepository
from repositories.manager import ManagerRepository
from repositories.schedule import ScheduleRepository